### ISSUE TITLE
Server-side functionality

### ISSUE THREAD

**Issue by rclai** [Slava/meteor-rethinkdb#17]
Is this supposed to work?

``` js
Cities.forEach(function (city) {
      return States.insert({ cityId: city('id'), name: Random.choice(['Florida', 'Georgia', 'New York', 'California', 'Wyoming', 'Kansas', 'Idaho', 'Ohio', 'Oregon', 'North Carolina', 'South Carolina']) }).run();
}).run();
```

```
RqlCompileError: Variable name not found in:
W20150520-15:54:40.448(0)? (STDERR)     at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.3.fkb8jk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20150520-15:54:40.448(0)? (STDERR)     at Insert.run (packages/simple:rethink/rethink.js:126:1)
W20150520-15:54:40.449(0)? (STDERR)     at Meteor.publish.Cities.orderBy.index (app/think.js:57:207)
W20150520-15:54:40.449(0)? (STDERR)     at new Func (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/ast.js:3287:17)
W20150520-15:54:40.450(0)? (STDERR)     at Function.<anonymous> (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/ast.js:3878:12)
W20150520-15:54:40.450(0)? (STDERR)     at Function.expr (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/util.js:39:16)
W20150520-15:54:40.450(0)? (STDERR)     at funcWrap (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/ast.js:34:19)
W20150520-15:54:40.451(0)? (STDERR)     at Array.map (native)
W20150520-15:54:40.451(0)? (STDERR)     at Table.RDBVal.forEach (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/ast.js:799:53)
W20150520-15:54:40.454(0)? (STDERR)     at Table.proto.(anonymous function) (packages/simple:rethink/monkey-patching.js:40:1)
W20150520-15:54:40.454(0)? (STDERR)     at Table.proto.(anonymous function) [as forEach] (packages/simple:rethink/monkey-patching.js:40:1)
W20150520-15:54:40.454(0)? (STDERR)     at [object Object].proto.(anonymous function) [as forEach] (packages/simple:rethink/monkey-patching.js:24:1)
W20150520-15:54:40.454(0)? (STDERR)     at app/think.js:56:12
W20150520-15:54:40.455(0)? (STDERR)     at app/think.js:70:3
W20150520-15:54:40.455(0)? (STDERR)     at /root/rethink-demo/.meteor/local/build/programs/server/boot.js:222:10
W20150520-15:54:40.455(0)? (STDERR)     at Array.forEach (native)
W20150520-15:54:40.455(0)? (STDERR)     - - - - -
W20150520-15:54:40.455(0)? (STDERR) r.table("states").insert({cityId: var_0("id"), name: "Oregon"})
W20150520-15:54:40.456(0)? (STDERR)                                   ^^^^^                        
W20150520-15:54:40.456(0)? (STDERR)     at RqlCompileError.RqlServerError (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/errors.js:39:13)
W20150520-15:54:40.456(0)? (STDERR)     at new RqlCompileError (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/errors.js:62:50)
W20150520-15:54:40.456(0)? (STDERR)     at mkErr (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/util.js:173:10)
W20150520-15:54:40.457(0)? (STDERR)     at TcpConnection.Connection._processResponse (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/net.js:128:16)
W20150520-15:54:40.457(0)? (STDERR)     at TcpConnection.Connection._data (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/net.js:105:12)
W20150520-15:54:40.457(0)? (STDERR)     at Socket.<anonymous> (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/net.js:505:32)
W20150520-15:54:40.457(0)? (STDERR)     at Socket.emit (events.js:95:17)
W20150520-15:54:40.457(0)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20150520-15:54:40.458(0)? (STDERR)     at Socket.emit (events.js:92:17)
W20150520-15:54:40.458(0)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20150520-15:54:40.458(0)? (STDERR)     at emitReadable (_stream_readable.js:423:5)
W20150520-15:54:40.458(0)? (STDERR)     at readableAddChunk (_stream_readable.js:166:9)
W20150520-15:54:40.458(0)? (STDERR)     at Socket.Readable.push (_stream_readable.js:128:10)
W20150520-15:54:40.458(0)? (STDERR)     at TCP.onread (net.js:529:21)
W20150520-15:54:40.459(0)? (STDERR) From previous event:
W20150520-15:54:40.459(0)? (STDERR)     at Insert.TermBase.run [as _run] (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/ast.js:131:12)
W20150520-15:54:40.459(0)? (STDERR)     at Insert.run (packages/simple:rethink/rethink.js:124:1)
W20150520-15:54:40.459(0)? (STDERR)     at Meteor.publish.Cities.orderBy.index (app/think.js:57:207)
W20150520-15:54:40.459(0)? (STDERR)     at new Func (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/ast.js:3287:17)
W20150520-15:54:40.459(0)? (STDERR)     at Function.<anonymous> (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/ast.js:3878:12)
W20150520-15:54:40.460(0)? (STDERR)     at Function.expr (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/util.js:39:16)
W20150520-15:54:40.460(0)? (STDERR)     at funcWrap (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/ast.js:34:19)
W20150520-15:54:40.460(0)? (STDERR)     at Array.map (native)
W20150520-15:54:40.460(0)? (STDERR)     at Table.RDBVal.forEach (/root/rethink-demo/.meteor/local/isopacks/simple_rethink/npm/node_modules/rethinkdb/ast.js:799:53)
W20150520-15:54:40.460(0)? (STDERR)     at Table.proto.(anonymous function) (packages/simple:rethink/monkey-patching.js:40:1)
W20150520-15:54:40.461(0)? (STDERR)     at Table.proto.(anonymous function) [as forEach] (packages/simple:rethink/monkey-patching.js:40:1)
W20150520-15:54:40.461(0)? (STDERR)     at [object Object].proto.(anonymous function) [as forEach] (packages/simple:rethink/monkey-patching.js:24:1)
W20150520-15:54:40.461(0)? (STDERR)     at app/think.js:56:12
W20150520-15:54:40.461(0)? (STDERR)     at app/think.js:70:3
W20150520-15:54:40.461(0)? (STDERR)     at /root/rethink-demo/.meteor/local/build/programs/server/boot.js:222:10
W20150520-15:54:40.461(0)? (STDERR)     at Array.forEach (native)
W20150520-15:54:40.462(0)? (STDERR)     at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.3.fkb8jk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150520-15:54:40.462(0)? (STDERR)     at /root/rethink-demo/.meteor/local/build/programs/server/boot.js:117:5
```

**Comment by rclai** [comment]
I also noticed that just doing

``` js
Cities.run();
```

doesn't work on the server.

**Comment by rclai** [comment]
I also tried using the `r` object to do the query and it gave me the same error.

``` js
r.table('cities').forEach(function (city) {
      return r.table('states').insert({ cityId: city('id'), name: Random.choice(['Florida', 'Georgia', 'New York', 'California', 'Wyoming', 'Kansas', 'Idaho', 'Ohio', 'Oregon', 'North Carolina', 'South Carolina']) }).run(Rethink._connection);
}).run(Rethink._connection);
```

**Edit**:

Nevermind, looks like I was doing this query wrong, it should be:

``` js
r.table('cities').forEach(function (city) {
      return r.table('states').insert({ cityId: city('id'), name: Random.choice(['Florida', 'Georgia', 'New York', 'California', 'Wyoming', 'Kansas', 'Idaho', 'Ohio', 'Oregon', 'North Carolina', 'South Carolina']) });
}).run(Rethink._connection);
```

**Comment by rclai** [comment]
Looks like consequently, this worked too:

``` js
Cities.forEach(function (city) {
      return States.insert({ cityId: city('id'), name: Random.choice(['Florida', 'Georgia', 'New York', 'California', 'Wyoming', 'Kansas', 'Idaho', 'Ohio', 'Oregon', 'North Carolina', 'South Carolina']) });
}).run();
```
